### ISSUE TITLE
DBconnect.php function​ ​__construct​()

### ISSUE THREAD

**Issue by WhyANameWhy** [Chpetrou/EuroCoinCollection#3]
Hello is there something missing in ​function​ ​__construct​()? I have a constants.php file but can't connect to a database. It doesn't even give me a error message.

**Comment by Chpetrou** [comment]
Hello,

> Hello is there something missing in ​function​ ​__construct​()?

No, it's just there by mistake and poor design.

As for the database, I'm using mysqli to connect to it. If there is an error, it should normally print it on some corner of the screen. 
If you don't see anything, try to remove the user login functionality along with the session redirects, so that it takes you directly to what is now **home.php**. Make that an **index.php** and see if you have a response.
Depending on what database you are using, you could also try changing the **mysqli** to **PDO** as the former only supports MySQL databases.
